---
CAMERA_TASK:
  TaskName: "Camera_Task"
  TaskEntryPtr: "camera_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_MEDIUM
  TaskPriority: TASK_PRIORITY_MEDIUM
  TaskHandle: "nullptr"
  Core: "M4"

M4_IPC_TASK:
  TaskName: "M4_IPC_Task"
  TaskEntryPtr: "m4_ipc_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_MEDIUM
  TaskPriority: TASK_PRIORITY_MEDIUM
  TaskHandle: "nullptr"
  Core: "M4"


M7_IPC_TASK:
  TaskName: "M7_IPC_Task"
  TaskEntryPtr: "m7_ipc_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_MEDIUM
  TaskPriority: TASK_PRIORITY_MEDIUM
  TaskHandle: "nullptr"
  Core: "M7"

TOF_TASK:
  TaskName: "TOF_Task"
  TaskEntryPtr: "tof_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_MEDIUM
  TaskPriority: TASK_PRIORITY_MEDIUM
  TaskHandle: "nullptr"
  Core: "M7"

INFERENCE_TASK:
  TaskName: "Inference_Task"
  TaskEntryPtr: "inference_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_MEDIUM
  TaskPriority: TASK_PRIORITY_HIGH
  TaskHandle: "nullptr"
  Core: "M7"

DEPTH_ESTIMATION_TASK:
  TaskName: "Depth_Estimation_Task"
  TaskEntryPtr: "depth_estimation_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_LARGE
  TaskPriority: TASK_PRIORITY_HIGH
  TaskHandle: "nullptr"
  Core: "M7"

STATE_CONTROLLER_TASK:
  TaskName: "State_Controller_Task"
  TaskEntryPtr: "state_controller_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_LARGE
  TaskPriority: TASK_PRIORITY_HIGH
  TaskHandle: "nullptr"
  Core: "M7"

RGB_TASK:
  TaskName: "RGB_Task"
  TaskEntryPtr: "rgb_task"
  PeriodicityInMS: 33
  ParametersPtr: 0
  StackSize: STACK_SIZE_SMALL
  TaskPriority: TASK_PRIORITY_LOW
  TaskHandle: "nullptr"
  Core: "M7"
